process:
  name: "yaml_preprocessor.process.name"
  description: "yaml_preprocessor.process.description"
  fields:
    on_success:
      name: "yaml_preprocessor.process.on_success.name"
      description: "yaml_preprocessor.process.on_success.description"
      selector:
        select:
          options:
            - reload
            - restart