process:
  description: "Process the YAML files and optionally perform an action on success."
  fields:
    on_success:
      description: "Select an action to perform after processing YAML: 'reload' to reload the core configuration, 'restart' to restart Home Assistant, or leave empty for no action."
      example: reload
      selector:
        select:
          options:
            - reload
            - restart
