process:
  name: "yaml_preprocessor.services.process.name"
  description: "yaml_preprocessor.services.process.description"
  fields:
    on_success:
      name: "yaml_preprocessor.services.process.on_success.name"
      description: "yaml_preprocessor.services.process.on_success.description"
