template:
  - sensor:
    - !include
        file: test/.sensor.yaml
        vars:
          name: Test Sensor One
          id: one
    - !include
        file: test/.sensor.yaml
        vars:
          name: Test Sensor Two
          id: two

script: !include scripts.yaml
