sensors:
  - platform: template
    sensors:
      test_sensor_1: !include
        file: test/.sensor.yaml
        vars:
          name: Test Sensor One
          id: one
      test_sensor_2: !include
        file: test/.sensor.yaml
        vars:
          name: Test Sensor Two
          id: two

scripts: !include_dir_list scripts
